'''
Created on Nov 22, 2018

@author: kjnether
'''

envs = ['TST', 'PRD']

FMESECRETLABEL_TEMPLATE = 'FME_{0}'
KIRKSECRETLABEL_TEMPLATE = 'KIRK_{0}'

SCHEDULE_REPO_LABEL = 'SCHEDULED_REPO'

SECRET_LABEL_TEMPLATE = 'DB_{0}'

SMTPSERVER = "SMTP_SERVER"
SMTPPORT = "SMTP_PORT"
EMAIL_TO = 'EMAIL_TO'
EMAIL_FROM = 'EMAIL_FROM'
EMAIL_SUBJECT = 'EMAIL_SUBJECT'

JENKINSURL = 'JENKINSURL'
