'''
Created on Nov 22, 2018

@author: kjnether
'''

envs = ['TST', 'PRD']

FMESECRETLABEL_TEMPLATE = 'FME_{0}'
KIRKSECRETLABEL_TEMPLATE = 'KIRK_{0}'

SCHEDULE_REPO_LABEL = 'SCHEDULED_REPO'

SECRET_LABEL_TEMPLATE = 'DB_{0}'
